# Generated by Django 2.2.5 on 2019-10-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_no', models.CharField(max_length=50)),
                ('Ticket_notes', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.IntegerField(null=True)),
                ('firstname', models.CharField(default='', max_length=25)),
                ('lastname', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=25)),
                ('Issuetype', models.CharField(default='', max_length=50)),
                ('Issue_Desc', models.CharField(default='', max_length=200)),
                ('Ticket_no', models.CharField(default='', max_length=25)),
                ('Ticket_status', models.CharField(default='', max_length=25, null=True)),
            ],
        ),
    ]
